name: GitHub Self-Updating Repository

on:
  #schedule:
  #- cron: '*/5 * * * *'
  #- cron: "0 0 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    web-deploy:
      name: 🎉 Create deployment artifact
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
        - name: 📂 Compile CSS and JS files
          run: |
            npm install
            npm run build
