name: GitHub Self-Updating Repository

on:
  #schedule:
  #- cron: '*/5 * * * *'
  #- cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GUETA_TOKEN }}
      - name: 📂 Deploy
        run: |
          git config user.email ${{ secrets.SECRET_GUETA_EMAIL }}
          git config user.name ${{ secrets.SECRET_GUETA_USERNAME_REPO }}
          git add --all
          git commit -m "Updating Project" || echo "No changes to commit"
      - name: 🎉 Push the updated branch
        run: |
          git push -f origin main
